name: Manual
on:
  workflow_dispatch: # 手動実行
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
        required: true
        description: Log level
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }} ${{ inputs.log-level }}"
